name: Entrypoint

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: log container node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/usr/local/bin/node"
          args: -v
      - uses: actions/checkout@v3
      - name: Run entrypoint script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "Entrypoint Script"
