name: Filter-devl
on:
  push:
    paths-ignore:
      - "prod/**"
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump expressions
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startsWith('hello', 'he') }}
          echo ${{ endsWith('lo', 'lo') }}
          echo ${{ format('hello {0} {1}{2}', 'World', '!', '!') }}
          echo 'prod success'
